---
# Make sure python is installed
- name: "Install Ansible requirements (Python)"
  hosts: all:!windows
  strategy: free
  gather_facts: False
  roles:
  - role: ansible-requirements
  tags: ['always']

- name: "Make sure windows hosts can be contacted"
  hosts: windows
  strategy: free
  gather_facts: False
  any_errors_fatal: true
  roles:
  - role: host-readiness
  tags: ['always', 'win', 'windows']

# Validate needs to gather facts
- hosts: all
  gather_facts: True
  roles:
  - role: validate
  - role: dsinfo
  tags:
  - validate
  any_errors_fatal: true
