# This hostfile has been generated by terraform.

[linux-ucp-manager-primary]
${linux_manager_primary}

[linux-ucp-manager-replicas]
${linux_manager_replicas}

[linux-dtr-worker-primary]
${linux_dtr_primary}

[linux-dtr-worker-replicas]
${linux_dtr_replicas}

[linux-workers]
${linux_workers}

[windows-workers]
${windows_workers}

[all:vars]
infra_stack=${infra_stack}
${load_balancers}
${extra_vars}
${cloudstor_plugin_version}
${docker_dtr_ca_file}
${docker_dtr_cert_file}
${docker_dtr_image_repository}
${docker_dtr_install_args}
${docker_dtr_key_file}
${docker_dtr_replica_id}
${docker_dtr_version}
${docker_ee_package_version}
${docker_ee_package_version_win}
${docker_ee_release_channel}
${docker_ee_repo}
${docker_ee_repository_url}
${docker_ee_package_url_win}
${docker_ee_subscriptions_centos}
${docker_ee_subscriptions_oracle}
${docker_ee_subscriptions_redhat}
${docker_ee_subscriptions_sles}
${docker_ee_subscriptions_ubuntu}
${docker_ee_version}
${docker_hub_id}
${docker_hub_password}
${docker_storage_driver}
${docker_storage_fstype}
${docker_storage_volume}
${docker_swarm_listen_address}
${docker_ucp_admin_password}
${docker_ucp_admin_username}
${docker_ucp_ca_file}
${docker_ucp_cert_file}
${docker_ucp_key_file}
${docker_ucp_image_repository}
${docker_ucp_install_args}
${docker_ucp_license_path}
${docker_ucp_version}
${dev_registry_username}
${dev_registry_password}
${use_dev_version}
${docker_engine_enable_remote_tcp}
${docker_engine_ca_file}
${docker_engine_ca_key_file}
${docker_worker_orchestration}

#
# High-level hosts (do not edit).
#

# UCP.
[ucp-primary:children]
linux-ucp-manager-primary

[linux-ucp:children]
linux-ucp-manager-primary
linux-ucp-manager-replicas

[ucp:children]
linux-ucp

# DTR.
[dtr-primary:children]
linux-dtr-worker-primary

[dtr-replicas:children]
linux-dtr-worker-replicas

[linux-dtr:children]
linux-dtr-worker-primary
linux-dtr-worker-replicas

[dtr:children]
linux-dtr

[linux]

#
# Linux Node Configuration
#
[linux-managers:children]
linux-ucp


[linux:children]
linux-managers
linux-workers
linux-dtr
ucp-load-balancer
dtr-load-balancer

[linux:vars]
ansible_become= yes
ansible_ssh_private_key_file=${private_key_file}

#
# Windows Node Configuration
#
[windows:children]
windows-workers

[windows:vars]
windows_enabled= yes
ansible_connection= winrm
ansible_winrm_server_cert_validation= ignore
ansible_become= no
ansible_winrm_operation_timeout_sec= 250
ansible_winrm_read_timeout_sec= 360
ansible_winrm_message_encryption= never

# Managers.
[managers:children]
ucp-primary
linux-managers

# Workers.
[workers:children]
linux-workers
linux-dtr
windows-workers

[load-balancers:children]
ucp-load-balancer
dtr-load-balancer

[ucp-load-balancer]
${linux_ucp_lbs}

[dtr-load-balancer]
${linux_dtr_lbs}
